# Base URL
baseurl: ""

# Site live URL
url: http://junhc.github.io

# Localhost 
# url: http://127.0.0.1:4000  

junhc:
  name: Junhc
  description: 岂止于博客

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments 

# Permalinks
permalink:        pretty

exclude: 
  - README.md
  - .gitignore
  - .sass-cache
  - LICENSE.md

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
